name: Test with Code Coverage
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        toolchain: [stable, nightly]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      run: |
        rustup toolchain add ${{ matrix.toolchain }} --component llvm-tools-preview
        rustup override set ${{ matrix.toolchain }}

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1

    - name: Install grcov for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
        mkdir -p ${HOME}/.local/bin/
        mv ./grcov ${HOME}/.local/bin/

    - name: Install grcov for Mac OS
      if: matrix.os == 'macos-latest'
      run: |
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
        curl -L https://github.com/mozilla/grcov/releases/download/v0.8.11/grcov-x86_64-apple-darwin.tar.bz2  | tar jxf -
        mkdir -p ${HOME}/.local/bin/
        mv ./grcov ${HOME}/.local/bin/

    # - name: Install grcov for Windows
    #   if: matrix.os == 'windows-latest'
    #   run: cargo install grcov

    - name: Run tests
      run: cargo test
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cinstrument-coverage'
        RUSTDOCFLAGS: '-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cinstrument-coverage'
        LLVM_PROFILE_FILE: 'report-%p-%m.profraw'

    - name: Generate code coverage
      run: grcov . --binary-path target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov

    - name: Upload coverage report to codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage.lcov
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
